site_name: Wiki-Code
site_url: https://deine-domain.de
site_author: Dein Name
site_description: Ein produktives Wiki-Projekt

theme:
  name: material
  language: de
  custom_dir: .overrides
  features:
    - navigation.instant
    - navigation.top
    - search.highlight
    - search.suggest

plugins:
  - search
  - macros
  - git-revision-date-localized:
      enable_creation_date: false  # optional
      fallback_to_build_date: true
      type: datetime
      locale: de_DE
      date_format: '%Y-%m-%d'

extra:
  social:
    - type: github
      link: https://github.com/umbassa-long/wiki-code

nav:
  - Home: index.md
  - Projekte:
      - Projekt 1: projekte/projekt1.md
      - Projekt 2: projekte/projekt2.md
  - Tools:
      - Tool 1: tools/tool1.md
  - Markdown: markdown.md
  - Hochladen: hochladen.md
  - Links: links/links.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed

extra_javascript:
  - https://giscus.app/client.js

extra_css:
  - stylesheets/extra.css
