theme:
  name: material
  language: de
  palette:
    # 1. Helles Schema (Die Sonne/Helle Ansicht)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'indigo'
      accent: 'teal'
      toggle:
        icon: material/brightness-7 # Das Symbol der Sonne
        name: Auf dunkles Schema wechseln
    # 2. Dunkles Schema (Der Mond/Dunkle Ansicht)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'indigo'
      accent: 'teal'
      toggle:
        icon: material/brightness-4 # Das Symbol des Mondes
        name: Auf helles Schema wechseln
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  # ... weitere features ...