site_name: Mein Minimal-Wiki
site_url: https://wiki-code.github.io/

theme:
  name: material
  language: de

nav:
  - Startseite: index.md

# Hier sind ALLE Erweiterungen deaktiviert, um Konflikte auszuschließen.
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.emoji