site_name: Wissensspeicher
site_url: https://wiki-code.github.io/
site_description: Mein Wissensspeicher
repo_url: https://github.com/umbassa-long/wiki-code
repo_name: GitHub

theme:
  name: material

  plugins:
  - macros
  - git-revision-date-localized:
      enabled: true
      type: timeago
      locale: de
      date_format: "%d. %B %Y"

  extra:
  revision:
    date: true

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.expand
    - content.tabs.link
    - toc.follow
    - navigation.footer
    - navigation.top

palette:
    - scheme: default # Helles Schema
      primary: light blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Zum dunklen Modus wechseln
    - scheme: slate # Dunkles Schema
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Zum hellen Modus wechseln
        
  # HIER DIE SCHRIFTART EINF√úGEN (Optional):
font:
  text: Roboto
  code: Roboto Mono

markdown_extensions:
  - attr_list # Wichtig f√ºr Attribute wie { .highlight }
  - admonition # Wichtig f√ºr Hinweis-Boxen (Info, Warning, etc.)
  - pymdownx.details # Wichtig f√ºr zusammenklappbare Bl√∂cke
  - pymdownx.superfences # Wichtig f√ºr erweitertes Code-Highlighting
  - pymdownx.tabbed:
      alternate_style: true # Wichtig f√ºr Tabs in Inhalten
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight: # Erweitertes Code-Highlighting
      anchor_linenums: true
  - pymdownx.snippets # Wichtig f√ºr das Einbetten von Code-Bl√∂cken
  - toc:
      permalink: true

nav:
  - Wissensspeicher: index.md
#  - üìò Inhalts√ºbersicht: summary.md
  - Code:
      - Welcome to MkDocs: code/welcome.md
  - Links:
      - Links & Ressourcen: links/links.md
  - Markdown:
      - Formatierung: markdown/formatierung.md
      - Grundlagen: markdown/grundlagen.md
      - Markdown-Tabellen: markdown/tabellen.md
      - Highlighting: markdown/admonition.md
      - Emoji: markdown/emoji.md
  - How Tos:
#       Diese Dateien m√ºssen existieren oder entfernen
#      - Projekt1: projekte/projekt1.md
 #     - Projekt2: projekte/projekt2.md
  - Tools:
      - Docker: tools/docker.md
      - Git: tools/git.md

