site_name: Denkwürdig
site_url: https://wiki-code.github.io/
#repo_url: https://github.com/Ihr-Github-Name/wiki-code # BITTE HIER IHRE REPO-URL EINFÜGEN!
#repo_name: GitHub

theme:
  name: material
  language: de
  palette:
    # 1. Helles Schema (Standard)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'indigo'
      accent: 'teal'
      toggle:
        icon: material/weather-sunny
        name: Auf dunkles Schema wechseln
    # 2. Dunkles Schema
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'indigo'
      accent: 'teal'
      toggle:
        icon: material/weather-night
        name: Auf helles Schema wechseln
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - content.action.top
    - content.code.copy
    - toc.follow

extra_css:
  - assets/extra.css

plugins:
  - macros
  - git-revision-date-localized:
      type: datetime
      timezone: Europe/Berlin
      locale: de

nav:
  - Wissensspeicher: index.md
  - Code:
    - Welcome to MkDocs: code/welcome.md
  - Links:
    - Links & Ressourcen: links/links.md
  - Markdown:
    - Formatierung: markdown/formatierung.md
    - Grundlagen: markdown/grundlagen.md
    - Markdown-Tabellen: markdown/tabellen.md
    - Highlighting: markdown/admonition.md
    - Emoji: markdown/emoji.md
  - How Tos:
    - Projekt1: projekte/projekt1.md
    - Projekt2: projekte/projekt2.md
  - Tools:
    - Docker: tools/docker.md
    - Git: tools/git.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  # Folgende Erweiterungen wurden aufgrund von Modul-Fehlern deaktiviert:
  # - attr_list
  # - pymdownx.md_in_html:
  #     markdown_extensions:
  #       - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg