site_name: Wissensspeicher
site_url: https://wiki-code.github.io/
site_description: Mein Wissensspeicher

theme:
  name: material

  nav:
  - Wissensspeicher: index.md
#  - ðŸ“˜ InhaltsÃ¼bersicht: summary.md
  - Code:
      - Welcome to MkDocs: code/welcome.md
  - Links:
      - Links & Ressourcen: links/links.md
  - Markdown:
      - Formatierung: markdown/formatierung.md
      - Grundlagen: markdown/grundlagen.md
      - Markdown-Tabellen: markdown/tabellen.md
      - Highlighting: markdown/admonition.md
      - Emoji: markdown/emoji.md
  - How Tos:
#       Diese Dateien mÃ¼ssen existieren oder entfernen
#      - Projekt1: projekte/projekt1.md
 #     - Projekt2: projekte/projekt2.md
  - Tools:
      - Docker: tools/docker.md
      - Git: tools/git.md

