site_name: Mein Minimal-Wiki
site_url: https://wiki-code.github.io/

theme:
  name: material
  language: de

nav:
  - Startseite: index.md

plugins:
    - macros
    - git-revision-date-localized:
        type: datetime
        timezone: Europe/Berlin
        locale: de

nav:
  - Wissensspeicher: index.md
  - Code:
    - Welcome to MkDocs: code/welcome.md
  - Links:
    - Links & Ressourcen: links/links.md
  - Markdown:
    - Formatierung: markdown/formatierung.md
    - Grundlagen: markdown/grundlagen.md
    - Markdown-Tabellen: markdown/tabellen.md
    - Highlighting: markdown/admonition.md
    - Emoji: markdown/emoji.md
  - How Tos:
    - Projekt1: projekte/projekt1.md
    - Projekt2: projekte/projekt2.md
  - Tools:
    - Docker: tools/docker.md
    - Git: tools/git.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg